-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lookomic`;

CREATE SCHEMA `lookomic`;
USE `lookomic` ;

-- -----------------------------------------------------
-- Table `lookomic`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lookomic`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lookomic`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(2000) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------

INSERT INTO product_category(category_name) VALUES ('ATAQUE DE LOS TITANES - GUIDE');
INSERT INTO product_category(category_name) VALUES ('ATTACK ON TITAN');
INSERT INTO product_category(category_name) VALUES ('BERSERK');
INSERT INTO product_category(category_name) VALUES ('BOKU NO HERO');
INSERT INTO product_category(category_name) VALUES ('DRAGON BALL');
INSERT INTO product_category(category_name) VALUES ('FAIRY TAIL');
INSERT INTO product_category(category_name) VALUES ('NARUTO');
INSERT INTO product_category(category_name) VALUES ('ONE PIECE');
INSERT INTO product_category(category_name) VALUES ('ONE PUNCH MAN');
INSERT INTO product_category(category_name) VALUES ('SAILOR MOON');
INSERT INTO product_category(category_name) VALUES ('SAILOR MOON SHORT STORIES');
INSERT INTO product_category(category_name) VALUES ('TOKYO REVENGERS');
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QATIT003', 'ataque de los titanes answers (guide book)', '¡Finalmente llega la tercera guía de Ataque de los Titanes! Y está llena de gran cantidad de información: un análisis minucioso de la batalla decisiva en el Distrito Shiganshina, entrevistas al maestro Isayama y nuevas ilustraciones de “Y si…” de los soldados en la preparatoria, entre otros interesantes apartados. Por si fuera poco, y para completar tu colección, también incluye dos modelos de papel: ¡El Titán Acorazado y el Titán Mujer! ¡No te la pierdas!', 'assets/images/products/ataque_de_los_titanes_guide/ataque_de_los_titanes_guide01.wepb', 1, 100, 1000, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QATIT002', 'ataque de los titanes n.2', '¡Por fin llega la segunda guía del mundo de Ataque de los Titanes! En ella encontrarás una entrevista a fondo con el maestro Isayama, quien nos habla a detalle sobre la creación del manga, así como reseñas sobre las batallas entre los titanes, una actualización de la guía de personajes y de los arcos de la historia, bocetos especiales y material inédito que se usó en el anime, además del primer manuscrito preliminar al manga que el maestro elaboró, y como un modelo de papel del Titán Colosal. ¡Imprescindible para todo fan!', 'assets/images/products/ataque_de_los_titanes_guide/ataque_de_los_titanes_guide02.wepb', 1, 100, 1500, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMAOT009', 'ataque de los titanes no. 9', 'Aunque capturaron con éxito a la titán mujer, ahora Eren y los demás deben enfrentar un nuevo misterio que duerme dentro de los muros de la ciudad. Además, en medio de la confusión, llega el anuncio de que la Muralla Rose ha caído…', 'assets/images/products/attack_on_titan/attack_on_titan09.webp', 1, 100, 2000, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMAOT008', 'ataque de los titanes no. 8', 'Luego de que el cuerpo de la titán mujer fuera devorado, ella reapareció cerca del grupo de Levi, a quien prácticamente aniquiló para capturar a Eren. De no haber sido por Mikasa, la titán habría tenido éxito, pero la victoria no significa mucho viendo a todos los soldados que perdieron. Ahora les queda un último recurso antes de que la policía militar ejecute a Eren: encontrar a la titán mujer dentro de una ciudad. ¡No te pierdas este espectacular Ataque de los titanes #8!', 'assets/images/products/attack_on_titan/attack_on_titan08.webp', 1, 100, 2500, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMAOT007', 'ataque de los titanes no. 7', 'La primera expedición de Eren en el cuerpo de investigación ha sido sanguinaria. Muchos soldados han muerto, pero no ha sido en vano, pues el plan secreto de Erwin Smith ha resultado: usando a Eren como carnada, lograron inmovilizar a la inteligente titán mujer y pronto verán qué humano está dentro. Sin embargo, deben hacerlo rápido, porque cada vez llegan más titanes a los límites del bosque, y la mujer titán podría no estar dispuesta a revelar sus secretos. Descúbrelo Ataque de los titanes #7 en los puntos de venta de Panini Manga.', 'assets/images/products/attack_on_titan/attack_on_titan07.webp', 1, 100, 3000, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMAOT006', 'ataque de los titanes no. 6', 'Gracias a una arriesgada jugada de Erwin y Levi, Eren ha sido puesto en custodia de un grupo especial del cuerpo de investigación. Sin embargo, luego del asesinato de los titanes capturados, el ambiente está lleno de desconfianza. Y aunque Armin parece haber descubierto algo al respecto de la conspiración, quizá no sobreviva para contarlo, ahora que una titán inteligente ha destruido a su grupo y va tras él. ¡Tu misión es conseguir Ataque de los titanes #6 en los puntos de venta de Panini Manga! ¡Cúmplela antes de que sea tarde!', 'assets/images/products/attack_on_titan/attack_on_titan06.webp', 1, 100, 3500, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMAOT005', 'ataque de los titanes no.5', 'Aunque Eren, en su forma titánica, selló el muro de Trost, ahora está encarcelado, pues la gente le tiene miedo. Erwin, comandante del cuerpo de investigación, tiene un plan que podría ser el primer rayo de luz para la humanidad en años, pero para llevarlo a cabo necesita que lo liberen. Descubre en Ataque de los Titanes #5 cómo fueron entrenados los cadetes del grupo de Eren, Mikasa y Armin, y qué ocurre con las conspiraciones del territorio central.', 'assets/images/products/attack_on_titan/attack_on_titan05.webp', 1, 100, 4000, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMAOT004', 'ataque de los titanes no.4', 'Se ha puesto en acción un plan para cerrar el hoyo que hay en la muralla Rosé: que Eren, convertido en titán, mueva una roca enorme para taparlo. Con la vida de la humanidad en los hombros, el titán Eren pierde entonces la noción de si mismo y comienza a enloquecer. Ni siquiera responde a las preguntas desesperadas de Armin...', 'assets/images/products/attack_on_titan/attack_on_titan04.webp', 1, 100, 4500, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMAOT002', 'ataque de los titantes n°2', 'nan', 'assets/images/products/attack_on_titan/attack_on_titan02.webp', 1, 100, 5000, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMAOT001', 'ataque de los titanes no.1', 'Este es un mundo controlado por los titanes... La humanidad, convertida en alimento de gigantes, ha construido paredes gigantescas, y pagó el poder evitar los ataques con su libertad. Sin embargo, la aparición del gran gigante destruye la paz simbólica que se había conseguido, y provoca el inicio de una guerra sin esperanza.
¡Este es el inicio de la esperada serie!', 'assets/images/products/attack_on_titan/attack_on_titan01.webp', 1, 100, 5500, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER011', 'berserk n.11', 'Luego de que Guts abandonara a la Banda del Halcón, Griffith provocó la ira del rey de Midland, por lo que fue capturado y torturado. Además, el ejército de Midland atacó a la Banda del Halcón. Un año después, y a punto de colapsar, la banda hizo a Kasca su líder y todos comenzaron una vida de fugitivos. Tras escuchar los rumores, Guts regresa para repeler a quienes perseguían a la Banda del Halcón. Él y Kasca aclaran todo entre ellos y se piden perdón el uno al otro.Guts y los demás rescatan a Griffith y en las cañerías acaban con Bakiraka, el asesino. ¡Después, el rey envía a los Caballeros del Perro Negro, encabezados por Wyald!', 'assets/images/products/berserk/berserk11.webp', 1, 100, 6000, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER010', 'berserk n.10', 'Luego de que Guts abandonara la Banda del Halcón, Griffith provocó la ira del rey al tener relaciones con su hija, la princesa Charlotte, por lo que fue capturado y torturado. Además, el ejército de Midland acorraló y atacó a la Banda del Halcón. Después de eso, los miembros de la banda vivieron como fugitivos durante un año con Kasca como líder. Tras escuchar los rumores, Guts regresa para ahuyentar a quienes perseguían a la Banda del Halcón y jura a sus integrantes que rescatará a Griffith. A la mañana siguiente, Kasca deja fluir sus sentimientos, Guts le hace el amor y, con ello, sus heridas emocionales surgen nuevamente.', 'assets/images/products/berserk/berserk10.webp', 1, 100, 6500, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER009', 'berserk n.9', 'Tras años de formar parte del grupo y vivir en camaradería, Guts finalmente decide abandonar la Banda del Halcón para encontrarse a sí mismo. Sin embargo, Griffith no lo dejará ir tan fácilmente y sólo le permitirá irse al derrotarlo en un duelo. Ahora el destino de la Banda del Halcón depende de Griffith, quien queda devastado tras la partida de Guts. ¿Podrá sobreponerse ante esta pérdida? ¿Qué encontrará Guts en esta etapa en solitario?', 'assets/images/products/berserk/berserk09.webp', 1, 100, 7000, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER008', 'berserk n.8', 'Comienza la batalla final entre Midland y Chuder por la supremacía, y la Banda del Halcón, el grupo de mercenarios más fuerte, se muestra más poderoso que nunca antes. Los 5 mil caballeros de la Banda del Halcón atacaron la impenetrable fortaleza de Doldrey, y llevaron a los protectores del castillo, los Caballeros del Rinoceronte Púrpura, a un lugar lejos de este. Mientras tanto, según el plan de Griffith, la tropa de Kasca está por infiltrarse en el castillo. Comienza una batalla contra el tiempo.', 'assets/images/products/berserk/berserk08.webp', 1, 100, 7500, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER007', 'berserk n.7', 'Después de caer por el acantilado, Kasca le cuenta a Guts su pasado, cómo conoció a Griffith y por qué es tan importante. Tras arriesgar la vida por ella, ¿finalmente Kasca aceptará a Guts como un miembro más de la Banda del Halcón? Además, Griffith y su grupo de mercenarios se preparan para conseguir lo que ningún ejército de Midland ha logrado: tomar el castillo de Doldrey. ¡Comienza la batalla! ¡Descubre el destino de Guts, el guerrero más fuerte, en Berserk 7!', 'assets/images/products/berserk/berserk07.webp', 1, 100, 8000, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER006', 'berserk n.6', 'Finalmente, Guts se ha ganado su lugar en la Banda del Halcón. La pelea contra Zodd casi le cuesta la vida a Griffith, quien expresa su agradecimiento a Guts después de su increíble actuación en el combate. Mientras tanto, la Banda del Halcón cada vez gana más reconocimiento en Midland por sus hazañas en el campo de batalla, pero esto causará gran molestia entre algunos miembros de la nobleza, quienes consideran que los integrantes de esta tropa no son más que vulgares mercenarios, y harán lo que sea necesario con tal de eliminarlos.', 'assets/images/products/berserk/berserk06.webp', 1, 100, 8500, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER005', 'berserk n.5', 'Se ha puesto en acción un plan para cerrar el hoyo que hay en la muralla Rosé: que Eren, convertido en titán, mueva una roca enorme para taparlo. 
Con la vida de la humanidad en los hombros, el titán Eren pierde entonces la noción de si mismo y comienza a enloquecer.
Ni siquiera responde a las preguntas desesperadas de Armin...', 'assets/images/products/berserk/berserk05.webp', 1, 100, 9000, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER004', 'berserk n.4', 'Luego de ser encontrado llorando bajo el cadáver de su madre, Guts es criado con crueldad por el mercenario Gambino, quien a base de mucho abuso, lo educa para ser un guerrero. 
Gracias a él, Guts aprende poderosas técnicas de espada y hace un debut espectacular en su primera batalla.
Sin embargo, no sabe por qué Gambino lo trata con tanta frialdad. 
Una noche, el compañero de batalla de Gambino, Donovan, decide atacar a Guts. ¡¿Por qué...?! ¡Es la historia de la juventud llena de guerra y emociones de Guts, el guerrero más fuerte!', 'assets/images/products/berserk/berserk04.webp', 1, 100, 9500, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER003', 'berserk n.3', 'Un hombre completamente vestido de negro que se hace llamar Guts, que tiene una mano artificial de hierro duro y que carga una espada gigantesca que supera su estatura, continúa su viaje con Puck, el elfo que se unió a él sin su permiso.
En una ciudad dominada por el miedo, sin planearlo, Guts se vende al mal y, durante una batalla contra el conde convertido en monstruo, que estaba masacrando a su propio pueblo, finalmente encuentra a los cinco miembros de La Mano de Dios, a quienes tanto había estado buscando.¿Por qué los está buscando?
¡Para descubrir ese secreto, la historia da un giro y vuelve al momento de su nacimiento...!', 'assets/images/products/berserk/berserk03.webp', 1, 100, 10000, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER002', 'berserk n.2', 'El malvado Conde usa sus poderes oscuros para transformar a un capitán de guardia derrotado en un horror inhumano para combatir a Guts, el Espadachín Negro.
Puck, el coqueto hada del tamaño de Guts, es capturado cuando intenta detener la ejecución de un viejo médico, y se le da como un regalo a la hija del conde, una niña dulce en una jaula dorada, encarcelada por su padre en su propia habitación. 
Guts, decidido a hacer carne picada del conde, asalta el castillo y esculpe una franja de destrucción empapada de sangre a través de los secuaces del conde.
Cara a cara con el Espadachín Negro por fin, el Conde revela su verdadera forma e incluso la espada de gran tamaño de Guts puede no ser lo suficientemente grande como para contender con esta monstruosidad demoníaca.', 'assets/images/products/berserk/berserk02.webp', 1, 100, 10500, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBER001', 'berserk n.1', 'Un hombre completamente vestido de negro que se hace llamar Guts, que tiene una mano artificial de hierro duro y que carga una espada gigantesca que supera su estatura.
En el lugar al cual se dirige llueve sangre y hay montañas de cadáveres apilados. Puck, un elfo que se mantiene a su lado desde que Guts le salvó la vida, quedó impresionado por su increíble fuerza, aunque a la vez le causa temor lo violento que es el mundo en el que él vive. 
Una horda de espíritus malignos que obstaculizan su camino. ¿acaso la marca que tiene en el cuello lo incita a buscar la venganza...? No te pierdas el primer tomo de esta increíble saga.', 'assets/images/products/berserk/berserk01.webp', 1, 100, 11000, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBOH035', 'my hero academia n.35', 'Es la última oportunidad para detener a All For One y cualquier error en la estrategia podría ser fatal para Japón e incluso para todo el planeta. Por eso, los héroes profesionales y los estudiantes de Yuei se reúnen para elaborar un plan en el que Midoriya es el principal señuelo. Sin embargo, los villanos saben que no pueden bajar la guardia y también se preparan para un nuevo ataque. Frases:- La gente vive para sonreír.- No hay mejor satisfacción que ver los frutos de tu esfuerzo.', 'assets/images/products/boku_no_hero/my_hero_academia_n.35.webp', 1, 100, 11500, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMBOH036', 'my hero academia n.36', 'La lucha para acabar con All For One y su ejército de villanos se complica para los héroes. Shoto debe llevar al máximo su singularidad para derrotar a un Toya corroído por el rencor y la venganza, mientras que el padre de ambos, Endeavor, lidia con sus fantasmas del pasado mientras trata de acabar con el enemigo. Además, si Bakugo continúa incrementando su poder de manera desmedida, su vida podría dar el último suspiro… ¿Estará dispuesto a sacrificarse con tal de acabar con los villanos?', 'assets/images/products/boku_no_hero/my_hero_academia_n.36.webp', 1, 100, 12000, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMDRB008', 'dragon ball n.8', 'El comandante Red envía al atroz mercenario Tao Pai Pai a la Tierra Sagrada de Karin, donde Goku logró encontrar la esfera del dragón de cuatro estrellas que le dejó su abuelo. Sin embargo, cuando este terrible bandido llega, asesina a Bora, el padre de Upa, y noquea a Goku. Ahora este chico tiene como misión subir a la Torre Karin para incrementar su fuerza con el agua sagrada y reunir las esferas para revivir a Bora. ¿Lo logrará? ¡Continúan la búsqueda en el tomo 8 de Dragon Ball!', 'assets/images/products/dragon_ball/dragon_ball08.webp', 1, 100, 12500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMDRB007', 'dragon ball n.7', '¡La Red Ribbon está tras los pasos de Goku y compañía! Uno de los generales de esta malvada asociación amenaza al maestro Roshi para que construya un radar de las esferas del dragón, pero no contaban con la presencia de Lunch, quien con un solo estornudo se convierte en una mujer temible. Además, mientras Goku y Bulma navegan por el océano encuentran un tesoro secreto, ¡y ahora deben conseguir el botín antes de que la cueva colapse y evitar que la Red Ribbon los atrape!', 'assets/images/products/dragon_ball/dragon_ball07.webp', 1, 100, 13000, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMDRB009', 'dragon ball n.9', 'Después de escalar la Torre Karin Goku se volvió más poderoso gracias al entrenamiento del maestro Karin. Con esta increíble fuerza fue capaz de derrotar al terrible mercenario Tao Pai Pai y recuperar las esferas que guardaba este bandido. Goku ahora se dirige hacia su siguiente objetivo: ¡Acabar con la Red Ribbon y reunir las esferas que faltan para revivir a Bora! ¿Lo logrará?¡No te pierdas el divertido tomo 9 de Dragon Ball que Panini Manga trae para ti!', 'assets/images/products/dragon_ball/dragon_ball09.webp', 1, 100, 13500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMDRB010', 'dragon ball n.10', 'Goku está por reunir las siete esferas del Dragón para hacer aparecer a Shenlong y poder revivir a Bora. La esfera que necesita… ¡la tiene Pilaf! Este villano piensa aprovecharse de la debilidad de Goku, ¡su cola! ¿Logrará derrotarlo? ¡Sigue la búsqueda en el tomo 10 de Dragon Ball!', 'assets/images/products/dragon_ball/dragon_ball10.webp', 1, 100, 14000, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMDRB011', 'dragon ball n.11', '¡Continúa el Torneo Mundial de las Artes Marciales! En esta ocasión se enfrentarán los discípulos de la Escuela de la Tortuga y los de la Escuela de la Grulla. El maestro Tsuru es uno de los más antiguos rivales del maestro Roshi, y en esta ocasión buscará no sólo humillar a sus adversarios en el más grande torneo de artes marciales, sino dar muerte a Goku en venganza por la muerte de su hermano, el mercenario Tao Pai Pai.', 'assets/images/products/dragon_ball/dragon_ball11.webp', 1, 100, 14500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMDRB006', 'dragon ball n.6', 'Goku sube la torre músculo del ejército de la Red Ribbon con el fin de rescatar al alcalde que se encuentra cautivo en el último piso, pero primero ¡debe derrotar al temible ninja Murasaki, quien se encuentra en el piso cuatro! Pero este no es el único enemigo que debe vencer, pues el general White ha preparado un sinfín de obstáculos para liquidar de una vez por todas a Goku y encontrar más fácilmente las codiciadas esferas del dragón. ¿Cumplirá su malvado cometido?', 'assets/images/products/dragon_ball/dragon_ball06.webp', 1, 100, 15000, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMDRB005', 'dragon ball n.5', '¡Continúa el torneo mundial de las artes marciales! Parece que Goku tiene ventaja sobre Jackie Chun, pero este anciano pronto le dará la vuelta al combate utilizando un sinfín de poderosas técnicas. ¿Quién se coronará como el mejor del mundo? Además, en su búsqueda por la esfera del dragón de su abuelo, Goku se encuentra con la malvada organización de la Red Ribbon, ¿qué sucederá en este encuentro? ¡Descúbrelo en el tomo cinco de Dragon Ball que Panini Manga trae para ti!', 'assets/images/products/dragon_ball/dragon_ball05.webp', 1, 100, 15500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMDRB004', 'dragon ball n.4', 'Continúa la final en el Torneo Mundial de Artes Marciales. Krillin y Yamcha son derrotados por Jackie Chun, (un participante desconocido, que no es ni más ni menos que el Maestro Roshi). Goku derrota al monstruo Giran, Nam perdió y no puede más llegar a la final. Ahora Goku y su maestro se enfrentan. ¿Goku descubrirá la verdadera identidad de Jackie Chun?', 'assets/images/products/dragon_ball/dragon_ball04.webp', 1, 100, 16000, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMDRB002', 'dragon ball n.2', 'Después de ayudar a Milk y a Ox Satán en el monte Frypan, Goku y Bulma se disponen a conseguir la última esfera no sin antes meterse en problemas con el Jefe Conejo y el terrible Pilaf que desea las esferas para dominar al Mundo. Veremos la primera aparición de Shenlong y aprenderemos porqué Goku y la Luna llena no son una buena combinación. Al final del tomo, Goku regresa con el Maestro Roshi para iniciar su entrenamiento.', 'assets/images/products/dragon_ball/dragon_ball02.webp', 1, 100, 16500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA013', 'fairy tail n.13', '¡Ha nacido un nuevo Fairy Tail! El gremio por fin ha sido reconstruido después de su destrucción, y Natsu y sus amigos experimentan un nuevo comienzo. ¡Entre nuevos miembros del gremio, entrevistas para revistas y otros "eventos", cada día es un caos! Sin embargo, hay alguien que está actuando sospechosamente. ¡¿Será que se aproxima a Fairy Tail una tormenta como no la había habido antes?!', 'assets/images/products/fairy_tail/fairy_tail13.webp', 1, 100, 17000, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA012', 'fairy tail n.12', '"“Una pregaria para la luz divina…” Para evitar que Zeref reviva, el Concilio Mágico decide utilizar Etherion. Por su lado, Erza decide sacrificar su vida para llevarse a Jellal consigo. Natsu y Erza son los únicos que quedan en la Torre del Cielo… Y con Etherion a punto de ser disparado todo se ve terrible. ¿Pero por qué Jellal no deja de sonreír demoniacamente? ¡Lo que sigue es un evento que nadie podría haber imaginado! ¡No te pierdas Fairy Tail #12!"', 'assets/images/products/fairy_tail/fairy_tail12.webp', 1, 100, 17500, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA011', 'fairy tail n.11', '¡Resulta que el objetivo de Jellal era usar la Torre del Cielo para revivir al mago más malvado en la historia del mundo, Zeref! Erza y los demás se disponen a detenerlo, pero Jellal usa al gremio de asesinos "Trinity Raven" para contratacar. Por otro lado, ¡el concilio mágico está a punto de aprobar el uso del cañon Etherion para destruir la Torre! ¿Qué pasará primero: la caída de Jellal o el disparo de Etherion? ¿Cuál será la conclusión de esta batalla? ¡Busca Fairy Tail #11 en todos los puntos de venta de Panini Manga!', 'assets/images/products/fairy_tail/fairy_tail11.webp', 1, 100, 18000, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA010', 'fairy tail n.10', '“A veces hay que descansar, ¿no?” Con esto en mente, Natsu y los demás se van a la playa. Sin embargo, la diversión dura solo hasta que ocurre una emergencia. Son atacados por sorpresa por una banda de locos, ¡quienes secuestran a Erza! El grupo se dirige a la “Torre del cielo”, donde los espera Jellal... ¡y donde se esconde el trágico pasado de Erza! ¡No te pierdas Fairy Tail #10!', 'assets/images/products/fairy_tail/fairy_tail10.webp', 1, 100, 18500, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA009', 'fairy tail n.9', 'Al concluir la guerra con Phantom, ¡Fairy Tail decide cambiar de actitud! Pero entre la decisión dictada por el Concilio Mágico y Lucy, quien, al sentirse responsable de la guerra, escribió una carta y regresó a casa, ¡los problemas se acumulan! Además, parece que Loke tiene un secreto increíble… El gremio vuelve a ser una locura, ¡así que no te pierdas Fairy Tail #9, que te espera en todos los puntos de venta de Panini Manga!', 'assets/images/products/fairy_tail/fairy_tail09.webp', 1, 100, 19000, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA008', 'fairy tail n.8', 'La batalla a muerte entre Fairy Tail y Phantom Lord continúa. Y ya han caído dos magos de Element 4, pero los restantes son los más fuertes. Además, Gajeel, el dragón de hierro, por fin peleará contra Natsu. ¿Quieres saber qué pasa cuando dos matadragones se enfrentan? ¿Y qué tal un combate entre Erza y el maestro de Phantom, José Porla? Todo esto y más en este emocionante Fairy Tail #8. ¡Pelea por él en todos los puestos de Panini Manga!', 'assets/images/products/fairy_tail/fairy_tail08.webp', 1, 100, 19500, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA007', 'fairy tail n.7', 'Luego de vencer a Deliora y de que el misterioso mago que estaba usando a Lyon para cumplir sus planes, el equipo de Natsu regresó a su ciudad. Sin embargo, encontraron algo terrible: el gremio mágico Phantom Lord atacó a Fairy Tail. Además, cuando Gray, Erza y los demás fueron a ajustar cuentas, cayeron directo en la trampa: dejaron sola a Lucy y ella fue secuestrada. Ahora un guerra se ha desatado y toda la ciudad podría ser destruida.', 'assets/images/products/fairy_tail/fairy_tail07.webp', 1, 100, 20000, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA006', 'fairy tail n.6', 'Natsu, Lucy y Happy vencieron a los secuaces de Lyon. Sin embargo, cuando Gray le reveló a éste que su antigua maestra, Ur, no murió años atrás sino que se convirtió en el hielo que detiene a Deliora, Lyon lo apuñaló con una espada de hielo, al tiempo que le revelaba que para él no había ahí sino un hielo insignificante. Aún con Erza ayudando en la batalla, la resurrección de Deliora está peligrosamente cerca, pues la luna morada sigue haciendo de las suyas.', 'assets/images/products/fairy_tail/fairy_tail06.webp', 1, 100, 1000, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA005', 'fairy tail n.5', 'Natsu, Lucy y Happy descubrieron que el hechizo que convierte a los aldeanos de la isla Galuna en demonios se debe a un rito para revivir a un demonio congelado. Y lo peor es que quien está detrás de todo es Lyon, el antiguo compañero de Gray, quien quiere sobrepasar a su antigua maestra, Ur, venciendo al demonio que ella selló al morir. Ya llegó Fairy Tail #5, donde se descubre más sobre la historia de Gray.', 'assets/images/products/fairy_tail/fairy_tail05.webp', 1, 100, 1500, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA004', 'fairy tail n.4', 'En el segundo piso de "Fairy Tail" existe un pizarrón de encargos sumamente peligrosos. ¡Los llaman trabajos nivel S! Se supone que solo cinco miembros tienen permiso para hacer estos trabajos, pero Natsu, Lucy y Happy sacaron uno sin permiso. El cliente es una isla maldita que convierte el cuerpo, el corazón y la mente en demonios de acuerdo al poder de la luna. Solo existe una manera de quitar la maldición... ¡¿destruir la luna?!', 'assets/images/products/fairy_tail/fairy_tail04.webp', 1, 100, 2000, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMFTA003', 'fairy tail n.3', 'Eisenwald, el gremio de magos liderado por el “Dios de la muerte”, Erigor, ha robado una flauta mágica. Este artefacto, “Lullaby”, tiene una maldición prohibida, que le causa la muerte a todos los que escuchan sus notas. ¿Será que este gremio negro, que odia a los legales, quiere llevar a cabo un indiscriminado asesinato en masa?...Como Fairy Tail sospecha algo, su equipo más fuerte, conformado por Natsu, Gray y Erza, ¡va a confrontarlos! ¡Y claro que Lucy y Happy están con ellos!', 'assets/images/products/fairy_tail/fairy_tail03.webp', 1, 100, 2500, 6, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR021', 'naruto n.21', 'Sasuke abandona Konoha, dejando atrás a sus amigos. ¡¿Acaso Orochimaru logró apoderarse de su mente?! Por órdenes de la quinta Hokage, Shikamaru, quien acaba de convertirse en chunin, convoca a Naruto, Neji, Kiba y Choji. ¡Los cinco salen en busca de Sasuke! Pero…Frases:Shikamaru es chunin. Debemos obedecerle.- ChojiYa empiezas a comportarte como el chunin que eres.- KibaSi puedes oler sangre, solo significa una cosa: un combate- Shikamaru.', 'assets/images/products/naruto/naruto21.webp', 1, 100, 3000, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR022', 'naruto n.22', 'Choji derrota a Jirobo y, lleno de orgullo, se desploma. ¡Shikamaru, Naruto, Neji y Kiba se enfrentan a los Cuatro del Sonido dispuestos a todo! ¡Neji desafía con el byakugan a Kidomaru, quien utiliza sus hilos como si fuera una araña! ¡Así comienza una batalla mortal! ¡Corre por Naruto #22, solo con Panini Manga!“Cuando te quedas si ideas, te mueres” – Kidomaru“Cualquier juego pierde sentido cuando ideas una estrategia para ganarlo” – Kidomaru“Ya que es un juego difícil de ganar, jugaré seriamente” - Kidomaru', 'assets/images/products/naruto/naruto22.webp', 1, 100, 3500, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR019', 'naruto n.19', '“Sí, justo esos sentimientos son los que no se van”. La existencia de Naruto fue lo que acabó con la indecisión de Tsunade! ¡Orochimaru y Kabuto contra Tsunade, Jiraiya, Naruto y Shizune. ¡Comienza una batalla sin igual! No te la pierdas, en Naruto #19!Lo más importante para un shinobi es que tenga las agallas para no rendirse.–JiraiyaTodo lo material se pudre al final.–OrochimaruSolo una vez, quisiera volver para apostar de nuevo por ti.–Tsunade', 'assets/images/products/naruto/naruto19.webp', 1, 100, 4000, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR023', 'naruto n.23', '¡Cuando creían que por fin habían rescatado a Sasuke, Kimimaro, un extraño enemigo, apareció frente a Naruto y los otros! Comienzan tres peleas mortales: Naruto contra Kimimaro, Shikamaru contra Tayuya, y Kiba y Akamaru contra Sakon. ¡Sean testigos de esta gran batalla! ¡No te pierdas esta batalla de diferentes escenarios en Naruto #23, que Panini Manga trae para ti!', 'assets/images/products/naruto/naruto23.webp', 1, 100, 4500, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR024', 'naruto n.24', '¡En medio de una intensa batalla entre Naruto y Kimimaro, la tina donde dormía Sasuke estalla! Sasuke aparece frente a Naruto, pero da media vuelta y se va corriendo. ¿Será muy tarde ya? ¡La batalla contra los del sonido todavía no termina! ¡¿Qué rumbo tomará ahora este enfrentamiento?! ¡Descúbrelo en Naruto #24, que Panini Manga trae para ti!', 'assets/images/products/naruto/naruto24.webp', 1, 100, 5000, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR025', 'naruto n.25', '¡Sasuke abandonó su aldea y a sus compañeros para ir con Orochimaru en busca de más poder! ¡Y Naruto está decidido a llevar a Sasuke de vuelta, pero...! ¡Además, en la cabeza de Sasuke, los recuerdos de Itachi, su hermano, surgen y se consumen como el fuego! ¿Qué pasará? ¡Averígualo en Naruto #25, que Panini Manga trae para ti!', 'assets/images/products/naruto/naruto25.webp', 1, 100, 5500, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR008', 'naruto n.8', 'La tercera fase del examen estaba a punto de comenzar cuando Naruto y sus compañeros descubrieron que deben superar una etapa de selección previa. Después de la inesperada salida de Kabuto, veinte aspirantes deberán luchar entre sí para ganarse un lugar en la siguiente fase. Todo esto y más en el Naruto #8, listo para ti en los puntos de venta de Panini Manga.', 'assets/images/products/naruto/naruto08.webp', 1, 100, 6000, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR007', 'naruto n.7', 'Con Naruto, Sasuke y Lee desmayados, y el trío de ninjas del sonido dispuestos a terminar con todos, Sakura ha decidido volverse fuerte para dejar de ser una carga para sus compañeros. Así, ha sacrificado su vanidad a favor de sus amigos. Además, no está sola, porque el equipo de Ino ha llegado y está decidió a ayudar. No te pierdas uno de los momentos más complicados de la segunda prueba de selección chunin en este Naruto #7. ¡Panini manga lo trajo para ti! ¿Te atreverás a leerlo?', 'assets/images/products/naruto/naruto07.webp', 1, 100, 6500, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR006', 'naruto n.6', 'Naruto, Sasuke y Sakura pasaron la estresante primera parte del examen de selección chunin: la prueba escrita, donde más que saber, debían recabar información de sus compañeros como verdaderos shinobi. Ahora ha empezado la segunda parte del examen: la prueba de supervivencia, la cual será realmente difícil, sobre todo cuando un misterioso ninja con poderes de serpiente se les interponga. Encuentra Naruto #6 en los puntos de venta de Panini Manga. ¿O vas a dejar que te lo ganen?', 'assets/images/products/naruto/naruto06.webp', 1, 100, 7000, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR005', 'naruto n.5', 'Luego de vencer a Zabuza y a Gato, Naruto y los demás volvieron a Konoha. Ahí, Kakashi los propuso como candidatos para presentar los exámenes de selección chunin, famosos por su dificultad. Aunque todo el equipo decidió participar, podrían tener complicaciones para inscribirse, ahora que Rock Lee, un misterioso shinobi que también presentará la prueba, ha retado a Sazuke a un duelo. ¡No te pierdas esta aventura!', 'assets/images/products/naruto/naruto05.webp', 1, 100, 7500, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMNAR004', 'naruto n.4', 'Con Sasuke caído, el zorro de nueve colas ha resurgido en Naruto, y ahora no solo Haku corre peligro, sino todos los que están en el puente. Además, Kakashi le demostrará a Zabuza cómo pelea sin usar el sharingan, y veremos el plan malévolo que Gato tuvo desde el comienzo. No te pierdas el gran final del arco “El puente de la valentía” en este Naruto #4.', 'assets/images/products/naruto/naruto04.webp', 1, 100, 8000, 7, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI012', 'one piece n.12', 'La leyenda ha comenzado. De nueva cuenta, los miembros de la tripulación renuevan su juramento y por fin llegan a Loguetown, la ciudad en la entrada a la “Grand Line”. Luffy y sus amigos escalan una, ¡¿montaña?! Y cuando se encontraban a punto de entrar, una gran barrera negra se levanta ante ellos. ¡Continúa la romántica aventura en busca del “One Piece”!', 'assets/images/products/one_piece/one_piece12.webp', 1, 100, 8500, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI011', 'one piece n.11', 'Luffy se enfurece por las declaraciones de Arlong porque trata a Nami como si fuera un objeto. ¡Un ataque de ira hará volar Arlong Park en pedazos y Nami volverá a sonreír desde lo profundo de su corazón! ¡Continúa la romántica aventura en busca del One Piece!', 'assets/images/products/one_piece/one_piece11.webp', 1, 100, 9000, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI010', 'one piece n.10', 'Tras escuchar el grito en el que Nami expresó sus sentimientos, ¡Luffy y sus amigos por fin se enfrentan a Arlong! ¡Pero cuando Luffy es lanzado al mar quedan en una crisis terrible! Entonces sus amigos, cada uno con sus propios sentimientos, se lanzan a un combate decisivo para salvar a Luffy. ¡Continúa la romántica aventura en busca del One Piece!', 'assets/images/products/one_piece/one_piece10.webp', 1, 100, 9500, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI009', 'one piece n.9', 'Arlong Park es una ciudad controlada por hombres pez que imponen su ley a todos los humanos. En esta ciudad a la que llegaron durante la persecución de Nami, Luffy y sus amigos se enfrentan a una verdadera sorpresa. ¿¡Los sentimientos de compañerismo conquistarán a Nami, quien lucha una solitaria batalla!? ¡Continúa la romántica aventura marina en busca del One Piece!', 'assets/images/products/one_piece/one_piece09.webp', 1, 100, 10000, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI008', 'one piece n.8', 'Luffy, con gran decisión, se enfrenta a Krieg. ¡Por fin llega a su final la impresionante batalla en el restaurante marítimo! La lucha es difícil porque ambos rivales son muy poderosos y decididos, en un momento determinado, Luffy toma la decisión de luchar sin temer a la muerte. Sanji recibe ayuda de Zeff y su tripulación para tomar una decisión que cambiará el rumbo de su vida. ¡Ya es hora de que Sanji vuelva a viajar por el mundo!', 'assets/images/products/one_piece/one_piece08.webp', 1, 100, 10500, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI007', 'one piece n.7', 'La flota de Don Krieg le exige enérgicamente al capitán Zeff que libere a los rehenes. En un acto despreciable, Luffy se vuelve loco y ataca a los enemigos, pero por alguna razón, Sanji no contraataca. ¡Detrás de ese extraño comportamiento, se esconde el misterioso pasado de Zeff! La batalla en el restaurante marítimo Baratie va subiendo de intensidad, hasta que Don Krieg decide usar su arma definitiva. ¡Continua esta romántica aventura marina en busca del One Piece!', 'assets/images/products/one_piece/one_piece07.webp', 1, 100, 11000, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI006', 'one piece n.6', 'Luffy y su tripulación hacen escala en el restaurante marítimo Baratie con la intención de encontrar a un cocinero. Mientras que Don Krieg (el almirante de una flota pirata de 50 embarcaciones) lleva a cabo su plan para secuestrar barcos; cierto personaje muy poderoso y lleno de misterio hace su aparición frente a la tripulación de Luffy…', 'assets/images/products/one_piece/one_piece06.webp', 1, 100, 11500, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI005', 'one piece n.5', 'Luffy por fin se enfrenta cara a cara con Kurahadol, ¡con el cruel mayordomo que resultó ser el capitán pirata Kuro! En la pendiente que lleva a la villa se ha desatado una batalla encarnizada que ha alcanzado su límite, ¡Ha llegado el momento de la verdad! Para salvar sus vidas, Kaya y los niños se internaron en el bosque pero no saben de la amenaza los sigue de cerca. ¡Usopp y Zoro deben apresurarse si quieren rescatarlos!', 'assets/images/products/one_piece/one_piece05.webp', 1, 100, 12000, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI004', 'one piece n.4', 'Luffy por fin se enfrenta cara a cara con Kurahadol, ¡con el cruel mayordomo que resultó ser el capitán pirata Kuro! En la pendiente que lleva a la villa se ha desatado una batalla encarnizada que ha alcanzado su límite, ¡Ha llegado el momento de la verdad! Para salvar sus vidas, Kaya y los niños se internaron en el bosque pero no saben de la amenaza los sigue de cerca. ¡Usopp y Zoro deben apresurarse si quieren rescatarlos!', 'assets/images/products/one_piece/one_piece04.webp', 1, 100, 12500, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI003', 'one piece n.3', 'El capitán Buggy “El payaso” y Luffy, tienen una espectacular pelea como solo podría suceder con dos poseedores de las habilidades de las frutas del diablo. Durante la pelea aprendemos más del pasado en común de Shanks y Buggy. Ahora que Nami y Zoro se han unido a la tripulación de Luffy es momento de continuar su camino hacia la “Grand Line”. Han desembarcado en una villa para buscar un barco más resistente y algo de comida. Ahí se encuentran con el orgulloso pero mentiroso Usopp y es gracias a él que conocen a Kaya, la persona más rica de la villa, a quien le piden un barco. Sin embargo, el mayordomo Kurahadol se entromete y Luffy tiene que renunciar trágicamente a su petición.', 'assets/images/products/one_piece/one_piece03.webp', 1, 100, 13000, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPI002', 'one piece n.2', 'Buggy “El payaso” (el villano favorito de Eiichiro Oda) y su tripulación creen que Luffy, Nami y Zoro pertenecen a una misma banda de ladrones que robó el mapa de la “Grand Line” y están decididos a hacerlos pagar por la ofensa. Luffy está decidido a hacer que Nami se una como su navegante pero antes de volver al mar deben enfrentarse a Moji, el vicecapitán y a Cabaji, el segundo oficial, los cuales demostrarán ser rivales con muchos trucos bajo la manga.', 'assets/images/products/one_piece/one_piece02.webp', 1, 100, 13500, 8, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPU013', 'one punch man n.13', 'No son el pulpo de 100 ojos, el ciempiés gigante o el descomunal ogro tetraóculo las peores amenazas para los habitantes de las ciudades. Tampoco lo es la recién constituida Asociación de Monstruos ni el mismo Garoh, el cazador de héroes que ha acabado con los más poderosos. El mayor peligro radica en unos pequeños organismos que en este tomo 13 de One Punch Man serán revelados. La magnitud de su poder puede hacerlos imbatibles, incluso para el mismo Saitama... ¿Qué esperas? Sumérgete ya en las páginas de este palpitante manga.', 'assets/images/products/one_punch_man/one_punch_man13.webp', 1, 100, 14000, 9, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPU012', 'one punch man n.12', 'Un cíclope con cuerpo de babosa y brazos que salen de su cabeza informa de la situación presente a su amo: los monstruos están mermando considerablemente las fuerzas de la Asociación de Héroes y han podido secuestrar al hijo de un importante benefactor de la Asociación. Todo el siniestro plan va viento en popa. Ajeno a estas maquinaciones perversas, Saitama continúa triunfando en el torneo de artes marciales, hasta llegar a la final. Y Garoh, el hombre monstruo, sigue buscando héroes para derrotarlos. ¿En qué momento confluirán estas tres grandes fuerzas en un titánico enfrentamiento final? ¡El tomo 12 de One Punch Man nos acerca a este ansiado desenlace!', 'assets/images/products/one_punch_man/one_punch_man12.webp', 1, 100, 14500, 9, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPU011', 'one punch man n.11', '¿Por qué los monstruos que pululan en las ciudades están ganando terreno? ¿Porque no hay suficientes héroes? ¿O porque aquellos que los enfrentan no saben trabajar en equipo, sino que cada uno busca su propia gloria para así poder subir de categoría en la Asociación de Héroes? ¿Y el desenfadado Saitama? ¿Aparecerá en el último minuto para vencer con su poderoso puño a las bestias destructoras? ¿O seguirá participando en el torneo de peleadores, para aprender artes marciales?', 'assets/images/products/one_punch_man/one_punch_man11.webp', 1, 100, 15000, 9, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPU010', 'one punch man n.10', 'La cacería de héroes iniciada por Garou va en aumento. Ni los héroes más fuertes y hábiles han podido derrotar al malvado hombre-monstruo. Saitama quiere enfrentarlo, pero antes deberá adentrarse en el peligroso mundo de las artes marciales avanzadas. ¿Logrará aprender tan rápido como van cayendo los héroes –y por si fuera poco, los ejecutivos de la Asociación–, a manos de Garou? Esperemos que un espeluznante ciempiés, la envidia de otros compañeros y un desfile de trajes de superhéroes no distraigan a Saitama de su misión.', 'assets/images/products/one_punch_man/one_punch_man10.webp', 1, 100, 15500, 9, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPU009', 'one punch man n.9', '¿Cómo es posible que Saitama vaya subiendo de posición en la Asociación de Héroes, si nunca hace alarde de sus hazañas? A él no le interesan las jerarquías de héroes, por eso puede rechazar la invitación de la prepotente Fubuki a trabajar para ella. Y tampoco necesita demostrar quién es mejor, como lo desafía el veloz Sonic. Pero llegará el momento en que tendrá que ponerse a la cabeza de todos, especialmente ahora que Garoh, el hombre que se cree monstruo, está derrotando a todos los héroes con tal de mostrar que el mal puede vencer al bien.', 'assets/images/products/one_punch_man/one_punch_man09.webp', 1, 100, 16000, 9, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPU008', 'one punch man n.8', 'Grandes monstruos feroces provenientes de las profundidades de la tierra, de lo hondo del mar o del espacio exterior. Criaturas infernales provistas de fuerza descomunal, garras letales y colmillos que trituran el acero. ¡Ojalá fueran los enemigos a vencer en este tomo 8 de One Punch Man! Al contrario, en esta ocasión, los grandes desafíos de Saitama serán confrontar a un héroe fortísimo que nunca ha peleado en su vida, encontrar a un gatito perdido y defender su estofado de langosta de un perverso grupo de delincuentes. ¿Sobrevivirá Saitama a tales peligros?Frases: • En muchas ocasiones, no es bueno ser tan grande. • Cuando el ataque ocurre en tu propio hogar, no te queda más que luchar. • Si tú eres el héroe de todos, es mejor que te hagas más fuerte. • No sé si estoy hecho para ser un héroe profesional. Creo que cada uno tiene una misión que cumplir.', 'assets/images/products/one_punch_man/one_punch_man08.webp', 1, 100, 16500, 9, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPU007', 'one punch man n.7', 'Aunque los héroes de clase “S” luchan contra los alienígenas invasores, Saitama se enfrenta al más poderoso de ellos, un monstruo capaz de destruir al planeta usando todo el potencial de su energía. Pero tras la batalla, deberá soportar los insultos y la envidia de algunos superdefensores ególatras. Por eso, cuando se le presenta la oportunidad, Saitama le dará una lección a la prepotente Asociación de Héroes.Frases: • En este mundo, se necesitan armas poderosas para preservar la paz. • No me explico por qué los héroes jóvenes generan tanto problema y son tan egoístas. • La policía también cumple con la función de los héroes, pero nosotros no nos jactamos de ello. • No entiendo a los héroes que salvan vidas solo para buscar el reconocimiento.', 'assets/images/products/one_punch_man/one_punch_man07.webp', 1, 100, 17000, 9, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPU005', 'one punch man n.5', 'El malvado Rey de las Profundidades amenaza con destruir Ciudad J y asesinar a todos sus habitantes. Diversos héroes de las más variadas categorías lo han enfrentado sin éxito. Sin embargo, ahora toca el turno de Genos y de Saitama. Parece uno de los retos más grandes a los que se han enfrentado. Su éxito podría significar una mejora en su clasificación, el reconocimiento de la gente y, por qué no, más ingresos como héroes. FRASES• Tienes mucha fuerza, pero eres muy lento para pelear contra mí. • Un héroe siempre debe ser valiente, fuerte y hermoso y debe poder vencer a los villanos con rapidez y astucia. • No es malo que ciertos héroes fracasen. Porque los demás se motivan para ser más fuertes. • Sé que no cuentan conmigo y que un héroe como yo no ayuda mucho, pero es mi tarea enfrentar el mal. • Si los héroes no vencen a los monstruos, no son héroes. Si se llaman héroes, deberían poder salvar vidas. • ¡En este movimiento está el secreto de la fuerza!• Es cierto, e', 'assets/images/products/one_punch_man/one_punch_man05.webp', 1, 100, 17500, 9, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPU004', 'one punch man n.4', 'Los héroes luchan con valentía. Los héroes derrotan al mal. Los héroes son reconocidos y admirados. Pero no ocurre esto con Saitama. En el volumen 4 de One punch man, nuestro héroe impedirá la destrucción de Ciudad-Z, así como miles de muertes. A cambio recibirá el rechazo de la gente y una humillación pública. Todo esto en medio de la aguerrida competencia de otros héroes por subir de categoría y de una invasión monstruosa proveniente del mar. Frases• Aunque nadie lo admire, no conozco una persona más increíble que usted, maestro.• Hay un caos en tu mente por pensar tanto en el fracaso. En los momentos críticos, lo mejor es no pensar tanto. • ¡No pensaré en el fracaso ni en las consecuencias! ¡Pondré toda mi atención y mi fuerza en este ataque!• Yo no soy héroe porque quiera sus halagos. ¡Soy héroe porque me da la gana!• Es admirable que estos perdedores se unan para apoyarse unos a otros. Hasta los criminales más violentos necesitan vivir en grupo. Eso los hace débile', 'assets/images/products/one_punch_man/one_punch_man04.webp', 1, 100, 18000, 9, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMOPU003', 'one punch man n.3', 'En busca de reconocimiento y popularidad, Saitama y Genos inician el proceso de calificación de la Asociación de Héroes. Aunque las pruebas no representan ningún desafío para ellos, son ubicados en categorías bajas. Por eso, deberán demostrar a los petulantes héroes que el verdadero talento está más allá de cualquier título. Frases:• La norma del héroe: deberás esforzarte mucho para no desperdiciar tu suerte. • ¡Aspiren siempre a ser héroes perfectos!• Las reglas de los duelos: esquivar todos los golpes que puedas, no dar ventajas, dejar de jugar y pelear en serio y continuar hasta que no puedas luchar. • ¡Estoy dispuesto a hacer lo que sea para volverme más fuerte!• ¿Quién decide cuáles son tus límites? ¿Será que no te has esforzado para ser realmente fuerte? • La fuerza que tienes ahora, ¿es lo que de verdad te limita?• ¿Tu yo de mañana jamás podrá vencer a tu yo actual? Sólo debes dejar atrás la frustración.', 'assets/images/products/one_punch_man/one_punch_man03.webp', 1, 100, 18500, 9, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMO012', 'sailor moon n.12', '¡La madre de todas las batallas comienza! Usagi se encuentra sola en la pelea definitiva contra Sailor Galaxia y sus esbirros. La desmotivación y desilusión de no tener a nadie por quién pelear, la embarga. Sin embargo, desde el futuro, Chibimoon y el Sailor Cuarteto llegan para luchar junto a ella. Además, Chibi Chibi y la princesa Kakyu le brindan su apoyo. Con renovadas fuerzas, enfrenta al peor enemigo de todos: Chaos. Súbitamente, aparece la forma definitiva de Sailor Moon del futuro. Finalmente, el desastre es contenido y un nuevo comienzo les espera a las sailors guardianas. FRASES1) "Nuestro valor no solo reside en el Sailor Crystal. Este cuerpo también es parte de nosotras. A este cuerpo es al que vemos y hablamos." Usagi Tsukino2) "Todos nacimos para vivir. Todas las formas de vida nacen para morir." Sailor Lethe3) "La oscuridad llama a la luz y la luz también llama a la oscuridad." Chibi Chibi4) "Podremos comenzar de nuevo una y otra vez." Sailor Cosmos', 'assets/images/products/salor_moon/sailor_moon12.webp', 1, 100, 19000, 10, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMO011', 'sailor moon n.11', 'Una aparente paz se respira en el aire y las sailors guardianas disfrutan de la escuela y de su vida. Sin embargo, un trágico suceso envuelve a Mamoru y Usagi "pierde" la memoria. En tanto, un famoso trío de cantantes es transferido a la escuela de las chicas: Three Lights. Por otro lado, un nuevo enemigo aparece y trae consigo muerte y dolor; no obstante, las sailors guardianas tendrán un aliado, proveniente de lo más lejano, en esta batalla final. ¡La más grande y definitiva batalla entre las sailors de todo el universo está por empezar!Frases:1) "¡La genialidad natural aparece cuando uno se olvida de la naturaleza!" Minako Aino2) "Siempre he buscado tu aroma y que mi voz llegue hasta a ti". Three Lights3) "¿La muerte llega así tan repentina e inesperadamente?" Usagi Tsukino', 'assets/images/products/salor_moon/sailor_moon11.webp', 1, 100, 19500, 10, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMO010', 'sailor moon n.10', 'En este cierre de arco, Dead Moon resulta ser más poderoso de lo pensado. Antiguas aliadas regresan con renovados poderes. Además, todas las sailors descubren más aspectos de sus vidas pasadas y, con nuevos bríos, y junto con Tuxedo Mask, ayudan a Sailor Moon y su nueva transformación a derrotar al enemigo. Helios ver cómo el Reino Dorado recobra su esplendor y se despide de su pequeña dama. Frases:1) "Abriremos el paso a un nuevo destino. Esa es la verdadera misión de las diez guardianas." Sailor Pluto2) "Mi sueño es proteger este planeta para que todos sean felices. Protegerlo junto a ti." Usagi Tsukino3) "Donde hay luz, habrá oscuridad. La oscuridad llama a la luz. ¡Y la luz llama a la oscuridad!" Reina Neherenia', 'assets/images/products/salor_moon/sailor_moon10.webp', 1, 100, 20000, 10, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMO009', 'sailor moon n.9', 'Usagi y Chibiusa sufren un extraño hechizo que invierte las edades de sus cuerpos, más no las de sus mentes. En tanto, Mamoru enferma gravemente y es hospitalizado; nadie sabe qué tiene. Por si fuera poco, un nuevo enemigo aparece y un pegaso llamado Helios pide ayuda a Chibiusa y encarga a las sailors que encuentren el Cristal Dorado para poder salvar tanto a Mamoru como a la Tierra. Nuevos peligros, pero también nuevos poderes están a la orden del día, ¿qué aventura les espera a las guardianas?Frases:1)', 'assets/images/products/salor_moon/sailor_moon09.webp', 1, 100, 1000, 10, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMO008', 'sailor moon n.8', 'Mistress 9 pone contra las cuerdas a las sailors, pero una aliada aparece: Hotaru, con todas sus fuerzas, intenta detenerla desde su interior. No obstante, lo que todos temían finalmente sucede: Sailor Saturn, la sailor de la destrucción, despierta. Con el fin de salvar al mundo de la destrucción, Sailor Moon decide hacer un último sacrificio. ¡No te pierdas este emocionante final de arco!Frases:1)', 'assets/images/products/salor_moon/sailor_moon08.webp', 1, 100, 1500, 10, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMO007', 'sailor moon n.7', 'Las sailors guardianas del sistema solar interior y exterior se reúnen y junto con eso, terribles secretos salen a relucir. Por otro lado, una nueva sailor que no debe ser despertada amenaza la vida del planeta... pero esa no es la mayor preocupación. El enemigo cada vez es más poderoso y pone en jaque a las guardianas, además, Chibiusa está al borde de la muerte. ¿Qué sucederá? ¡Pues averígualo en esta séptima entrega de tu manga favorito!', 'assets/images/products/salor_moon/sailor_moon07.webp', 1, 100, 2000, 10, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMO006', 'sailor moon n.6', '¡Amenaza por partida doble! Un nuevo enemigo aparece y unas sailors guardianas desconocidas muestran su apatía por las sailors que conocemos. Por otro lado, Usagi y Mamoru sienten un titubeo en su relación a causa de dos personas bastante misteriosas. En tanto, una aliada regresa, aunque se ignora la razón. ¿Quién será? ¡Descúbrelo en la sexta entrega de Pretty Guadian Sailor Moon!', 'assets/images/products/salor_moon/sailor_moon06.webp', 1, 100, 2500, 10, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMO004', 'sailor moon n.4', 'Un nuevo enemigo mucho más poderoso amenaza no solo a las sailors guardianas, sino al planeta completo. En tanto, Usagi sufre tanto por la pérdida de sus amigas como por la relación odio-¿amor? que sostiene con Chibiusa. Para salvar a sus compañeras, ella, junto con Venus y Tuxedo Mask viajarán al futuro ¡y conocerán algo insólito! ¿Qué crees que sea? ¡Adquiere esta nueva entrega de Pretty Guardian Sailor Moon y descúbrelo por ti mismo!', 'assets/images/products/salor_moon/sailor_moon04.webp', 1, 100, 3000, 10, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMO003', 'sailor moon n.3', 'La batalla con Metallia por fin comienza. Durante ella, conoceremos más del pasado de Mamoru y Usagi y sabremos qué es eso que los une tanto. La pelea se torna violenta y con resultados tristes, pero... Por otro lado, la llegada de una misteriosa niña colma la poca paciencia de Usagi y algo terrible sucede, ¿qué será? No te quedes con la duda y compra este nuevo tomo de Pretty Guadian Sailor Moon!', 'assets/images/products/salor_moon/sailor_moon03.webp', 1, 100, 3500, 10, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMS002', 'sailor moon short stories n.2 (de 2)', '¿Cuántas veces has deseado algo tanto que se vuelve realidad? Luna se enamora de un humano, pero sufre por no ser correspondida. Su ferviente súplica le concede unos instantes de felicidad. En tanto, Rei decide cerrar su corazón al amor, pero con justa razón. Y tenemos un vistazo al futuro de las Sailors como mujeres adultas. No te pierdas este último volumen de Short Stories.', 'assets/images/products/sailor_moon_short_stories/sailor_moon_short_stories02.webp', 1, 100, 4000, 11, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QMSMS001', 'sailor moon short stories n.1 (de 2)', '¡Las chicas también necesitan divertirse! Y, por supuesto, las Sailors Guardianas no son la excepción. Disfruta esta nueva entrega de Naoko Takeuchi en la que apreciarás el otro lado de tus heroínas favoritas: las estudiantes que sufren por los exámenes, las chicas que buscan ser aceptadas por la sociedad, los juegos entre amigos… ¡No te pierdas estas pequeñas, pero cautivantes historias, de Sailor Moon y sus amigas!', 'assets/images/products/sailor_moon_short_stories/sailor_moon_short_stories01.webp', 1, 100, 4500, 11, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QTKRE012', 'tokyo revengers n.12', 'Takemichi tiene una batalla decisiva contra la brutal banda de motociclistas: los Black Dragons. Pero Kisaki lo traiciona, ¡y ahora Hakkai y Yuzuha están en peligro! Para salvarlos, Mitsuya lucha contra Taiju, pero Inui, uno de los Black Dragons, lo deja fuera de combate tras un ataque sorpresa. Aun con su abrumadora desventaja, Takemichi pone su vida en juego para desafiar al monstruoso Taiju. ¡La batalla navideña llega a su clímax!Frases:1. “Esta situación es imposible. Taiju es un monstruo” – Mistuya2. “¡Mitsuya-kun! ¡Hakkai! ¡No podré durar mucho más! ¡Apúrense! – Takemichi3. “Quería proteger a mi familia… a Yuzuha. Pero… no tenía las agallas.” – Hakkai', 'assets/images/products/tokyo_revengers/tokyo_revengers12.webp', 1, 100, 5000, 12, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QTKRE013', 'tokyo revengers n.13', '¡El volumen 13 de la historia de suspenso con saltos en el tiempo!
¡El conflicto de Navidad llego a su fin!La misión tuvo éxito y no se perdió ninguna vida. Despues de que Takemichi logra su objetivo, frente a él aparece Hinata, de quien se había separado.Aún con su abrumadora desventaja, Takemichi pone su vida en juego para desafiar al monstruo Taiju.¿Qué es lo que quiere Hina?¿Y cuál será el siguiente movimiento de Kisaki!', 'assets/images/products/tokyo_revengers/tokyo_revengers13.webp', 1, 100, 5500, 12, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QTKRE014', 'tokyo revengers n.14', '¡El volumen 14 de la historia de suspenso con saltos temporales!
Tras completar su misión, Takemichi salta doce años hacia el presente. ¡Pero no sabe que allí le espera el peor futuro de todos los que ha visto! Finalmente, Takemichi logra reencontrarse con Mikey en el presente. Su reunión esconde una cruel realidad, además de una impactante revelación.', 'assets/images/products/tokyo_revengers/tokyo_revengers14.webp', 1, 100, 6000, 12, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QTKRE015', 'tokyo revengers n.15', '¡El volumen 15 de la historia de suspenso con saltos temporales!
Takemichi regresa al pasado jurando cumplir su promesa de convertirse en el líder de Tokio Manji para cambiar el futuro. Mientras tanto, una enorme banda nunca antes vista, Yokohama Tenjiku, comienza su ataque contra Tokio Manji. Es el comienzo del mayor y último conflicto de Tokio Manji: ¡la sublevación de Kanto!', 'assets/images/products/tokyo_revengers/tokyo_revengers15.webp', 1, 100, 6500, 12, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('QTKRE016', 'tokyo revengers n.16', '¡EL volumen 16 de la historia de suspenso con saltos en el tiempo! Después de conseguir información sobre la pandilla de Yokohama conocida como Tenjiku, y de averiguar más sobre su líder, Izana Kurokawa, Takemichi regresa del pasado. Pero ahora ya no hay manera de regresar al futuro.¡Por fin comienza la última batalla de Takemichi!', 'assets/images/products/tokyo_revengers/tokyo_revengers16.webp', 1, 100, 7000, 12, NOW());